StringLiterals:
  Enabled: false

Style/IndentationWidth:
  # Number of spaces for each indentation level.
  Width: 4

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
